name: show_me_the_gains
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  lottie: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5  

flutter:
  uses-material-design: true
  assets:
    -  lib/assets/
    -  lib/assets/lottie/